In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("diamonds.csv", index_col=0)
data.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53940 entries, 1 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.5+ MB

In [6]:
num=int(len(data)*0.8)
num

43152

In [7]:
data2=data[num:]

In [8]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10788 entries, 43153 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    10788 non-null  float64
 1   cut      10788 non-null  object
 2   color    10788 non-null  object
 3   clarity  10788 non-null  object
 4   depth    10788 non-null  float64
 5   table    10788 non-null  float64
 6   price    10788 non-null  int64
 7   x        10788 non-null  float64
 8   y        10788 non-null  float64
 9   z        10788 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 927.1+ KB

In [10]:
data2['cut'].value_counts()

Ideal        4629
Very Good    2534
Premium      2238
Good         1002
Fair          385
Name: cut, dtype: int64

In [11]:
data3=data2[(data2['cut']=='Fair') & (data2['carat']>=1)]
data3

       carat   cut color clarity  depth  table  price     x     y     z
46576   1.00  Fair     J      I1   65.0   59.0   1784  6.27  6.17  4.05
46785   1.00  Fair     I      I1   68.6   56.0   1805  6.20  6.08  4.22
48260   1.00  Fair     G      I1   67.3   57.0   1954  6.26  6.12  4.18
48607   1.00  Fair     I      I1   66.9   57.0   1997  6.15  6.03  4.09
48873   1.00  Fair     I      I1   64.5   58.0   2035  6.33  6.10  4.01
48879   1.01  Fair     E      I1   64.5   54.0   2036  6.31  6.22  4.03
48885   1.04  Fair     I      I1   67.3   56.0   2037  6.34  6.23  4.22
49465   1.00  Fair     I      I1   65.4   57.0   2112  6.28  6.20  4.08
49496   1.00  Fair     J     SI2   69.9   61.0   2117  6.13  5.86  4.23
49585   1.04  Fair     F      I1   65.4   60.0   2134  6.39  6.30  4.15
50317   1.06  Fair     I      I1   64.5   57.0   2239  6.47  6.33  4.13
50583   1.00  Fair     F      I1   68.0   57.0   2280  6.14  6.05  4.15
50679   1.01  Fair     G      I1   64.5   56.0   2287  6.32  6.26  4.06
50718   1.05  Fair     H      I1   61.8   57.0   2293  6.51  6.40  3.99
51008   1.00  Fair     G     SI2   70.2   58.0   2326  6.00  5.73  4.13
51102   1.17  Fair     I      I1   64.5   59.0   2336  6.67  6.47  4.25
51140   1.01  Fair     I      I1   56.1   63.0   2342  6.70  6.65  3.74
51446   1.07  Fair     G      I1   64.8   56.0   2375  6.53  6.43  4.20
51463   1.20  Fair     I      I1   66.7   57.0   2376  6.57  6.05  4.37
51464   1.20  Fair     I      I1   65.1   55.0   2376  6.65  6.59  4.31
51465   1.20  Fair     G      I1   66.6   57.0   2376  6.57  6.50  4.34
51625   1.05  Fair     I      I1   61.8   66.0   2396  6.48  6.37  3.97
51627   1.21  Fair     I      I1   65.0   58.0   2396  6.65  6.59  4.30
51684   1.00  Fair     G      I1   64.9   56.0   2398  6.20  6.14  4.01
52423   1.30  Fair     H      I1   64.4   57.0   2512  6.93  6.86  4.44
52539   1.00  Fair     H     SI2   67.8   53.0   2530  6.08  6.02  4.10
52806   1.30  Fair     E      I1   66.5   58.0   2571  6.79  6.75  4.50
52994   1.29  Fair     H      I1   67.7   62.0   2596  6.69  6.59  4.50
53147   1.20  Fair     F      I1   65.7   56.0   2622  6.65  6.58  4.35
53339   1.20  Fair     G      I1   64.4   55.0   2655  6.77  6.61  4.31
53496   1.01  Fair     J     SI2   66.9   58.0   2683  6.13  6.07  4.08
53699   1.05  Fair     H     SI2   64.8   55.0   2717  6.39  6.32  4.12
53746   1.00  Fair     G      I1   61.7   57.0   2723  6.39  6.28  3.91
53864   1.00  Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53880   1.04  Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07

In [12]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 35 entries, 46576 to 53880
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    35 non-null     float64
 1   cut      35 non-null     object
 2   color    35 non-null     object
 3   clarity  35 non-null     object
 4   depth    35 non-null     float64
 5   table    35 non-null     float64
 6   price    35 non-null     int64
 7   x        35 non-null     float64
 8   y        35 non-null     float64
 9   z        35 non-null     float64
dtypes: float64(6), int64(1), object(3)
memory usage: 3.0+ KB

In [13]:
print(np.max(data3['price']))

2745