In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Cars93.csv", index_col=0)
data.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,Front,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 93 entries, 1 to 93
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        93 non-null     object
 1   Model               93 non-null     object
 2   Type                93 non-null     object
 3   Min.Price           93 non-null     float64
 4   Price               93 non-null     float64
 5   Max.Price           93 non-null     float64
 6   MPG.city            93 non-null     int64
 7   MPG.highway         93 non-null     int64
 8   AirBags             93 non-null     object
 9   DriveTrain          93 non-null     object
 10  Cylinders           93 non-null     object
 11  EngineSize          93 non-null     float64
 12  Horsepower          93 non-null     int64
 13  RPM                 93 non-null     int64
 14  Rev.per.mile        93 non-null     int64
 15  Man.trans.avail     93 non-null     object
 16  Fuel.tank.capacity  93 non-null     float64
 17  Passengers          93 non-null     int64
 18  Length              93 non-null     int64
 19  Wheelbase           93 non-null     int64
 20  Width               93 non-null     int64
 21  Turn.circle         93 non-null     int64
 22  Rear.seat.room      91 non-null     float64
 23  Luggage.room        82 non-null     float64
 24  Weight              93 non-null     int64
 25  Origin              93 non-null     object
 26  Make                93 non-null     object
dtypes: float64(7), int64(11), object(9)
memory usage: 20.3+ KB

In [4]:
data2=data[data['Luggage.room'].notnull()]
data2

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,Front,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,None,Front,...,4,163,93,63,34,26.0,10.0,2240,non-USA,Volkswagen Fox
90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,Front,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,Front,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,Rear,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,Front,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [5]:
med=np.median(data2['Luggage.room'])
med

14.0

In [6]:
before=np.mean(data2['Luggage.room'])
before

13.890243902439025

In [7]:
data['Luggage.room']=np.where(data['Luggage.room'].isnull(), med, data['Luggage.room'])

In [8]:
after=np.mean(data['Luggage.room'])
after

13.903225806451612

In [9]:
print(after-before)

0.012981904012587364